Loading tensorflow-gpu/py3/1.14-openmpi
  Loading requirement: cuda/10.1.1 nccl/2.4.2-1+cuda10.1 cudnn/10.1-v7.5.1.10
    gcc/8.3.1 openmpi/4.0.2-cuda
+ cd /linkhome/rech/genimt01/uba22to/NADIR_TOOLS/scripts
+ python -u build_Dataset.py 5 GULFSTREAM training
Traceback (most recent call last):
  File "build_Dataset.py", line 25, in <module>
    nadir=NADIR_nadir.init2(domain,date,date1_nadir,date2_nadir,id_phase)
  File "/linkhome/rech/genimt01/uba22to/NADIR_TOOLS/nadir_tools/mods/class_NADIR_nadir.py", line 129, in init2
    return cls(list_files,domain,dateref)
  File "/linkhome/rech/genimt01/uba22to/NADIR_TOOLS/nadir_tools/mods/class_NADIR_nadir.py", line 88, in __init__
    self.data = xr.open_mfdataset(list_files, preprocess=self.preprocess2)
  File "/linkhome/rech/genimt01/uba22to/.local/lib/python3.7/site-packages/xarray/backends/api.py", line 911, in open_mfdataset
    datasets = [preprocess(ds) for ds in datasets]
  File "/linkhome/rech/genimt01/uba22to/.local/lib/python3.7/site-packages/xarray/backends/api.py", line 911, in <listcomp>
    datasets = [preprocess(ds) for ds in datasets]
  File "/linkhome/rech/genimt01/uba22to/NADIR_TOOLS/nadir_tools/mods/class_NADIR_nadir.py", line 43, in preprocess2
    if re.search(nm_sat[i],path)][0]
IndexError: list index out of range
